name: corbanmailloux
markdown: redcarpet
highlighter: rouge
encoding: UTF-8

url: https://alittleteapot.im

# Owner/author information
owner:
  name:           Corban
  full-name:      Corban Mailloux

gems:
  - jekyll-sitemap

# Limit what is hosted on the site.
exclude: ["runServer.bat", "CNAME", "README.md", ".gitignore"]
